services:
 multitrader:
  container_name: multitrader
  env_file: .env
  build:
      context: .
      dockerfile: Dockerfile
  restart: unless-stopped
  ports:
   - "80:80"
  networks:
   - multitrader

 multitrader-db:
   image: postgres:14-alpine
   env_file: .env
   restart: unless-stopped
   tty: true
   networks:
     - multitrader
   ports:
     - "5432:5432"
   volumes:
     - /mnt/multitrader-db:/var/lib/postgresql/data
     - /tmp/dump:/tmp/dump

networks:
  multitrader:
