"""
Django settings for multy_trader project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config as cnf

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = cnf("SECRET_KEY")
FIELD_ENCRYPTION_KEY = cnf("FERNET_KEY")
TG_TOKEN = cnf("TG_TOKEN")
BYBIT_API_KEY = cnf("BYBIT_API_KEY")
BYBIT_SECRET_KEY = cnf("BYBIT_SECRET_KEY")

GATE_HOST = cnf("GATE_HOST")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = cnf("DEBUG")
GATE_KEY= cnf("GATE_KEY")
GATE_SECRET_KEY= cnf("GATE_KEY")
MEXC_API_KEY=cnf("MEXC_API_KEY")
MEXC_API_SECRET=cnf("MEXC_API_SECRET")

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = 'trader.CustomUser'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trader.apps.TraderConfig',
    'exchange.apps.ExchangeConfig',
    'trade.apps.TradeConfig',
    'analytics.apps.AnalyticsConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'multy_trader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'multy_trader.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': cnf('ENGINE_DB'),
        'NAME': cnf('NAME_DB'),
        'USER': cnf('USER_DB'),
        'PASSWORD': cnf('PASSWORD_DB'),
        'HOST': cnf('HOST_DB'),
        'PORT': cnf('PORT_DB'),
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

JAZZMIN_SETTINGS = {
    "user_avatar": None,
    "site_title": "Мультитрейдер",
    "site_header": "Мультитрейдер",
    "site_brand": "Мультитрейдер",
    "welcome_sign": "Добро пожаловать в Мультитрейдер",
        "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "exchange.Exchange": "horizontal_tabs",
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "trader.ExchangeAccount":"fa-regular fa-address-card",
        "trader.Proxy":"fa-solid fa-mask",
        "trader.CustomUser":"fa-solid fa-house-user",
        "trade.Entry":"fa-solid fa-hand-holding-dollar",
        "exchange.Exchange":"fa-solid fa-arrow-trend-up",
        "exchange.WalletPair":"fa-solid fa-coins"
    },
    "user_display": "username",
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


BASE_URL_MEXC="https://api.mexc.com"
BASE_URL_GATE="https://api.gateio.ws"

API_ENDPOINT_GATE="/api/v4/spot/tickers"
API_ENDPOINT_MEXC="/api/v3/ticker/24hr"
