# Generated by Django 5.2.4 on 2025-08-15 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='BTC_USDT', max_length=10)),
                ('current_bid', models.FloatField()),
                ('current_ask', models.FloatField()),
                ('spread', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Стакан.',
                'verbose_name_plural': 'Стаканы.',
                'db_table': 'order_book',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WaletPairs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Слаг пары', max_length=255, verbose_name='Слаг пары')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Валютная пара.',
                'verbose_name_plural': 'Валютные пары',
                'db_table': 'walet_pairs',
                'ordering': ('-created_at',),
            },
        ),
    ]
