# Generated by Django 5.2.4 on 2025-07-16 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaletPairs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор публикации.', primary_key=True, serialize=False, verbose_name='ID публикации.')),
                ('slug', models.CharField(help_text='Заголовок рубрики', max_length=255, verbose_name='Заголовок рубрики.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Валютная пара.',
                'verbose_name_plural': 'Валютные пары',
                'db_table': 'walet_pairs',
                'ordering': ('-created_at',),
            },
        ),
    ]
