# Generated by Django 5.2.4 on 2025-07-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='BTC_USDT', max_length=10)),
                ('current_bid', models.FloatField()),
                ('current_ask', models.FloatField()),
                ('spread', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
