# Generated by Django 5.2.4 on 2025-07-16 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0003_orderbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderbook',
            options={'ordering': ('-created_at',), 'verbose_name': 'Стакан.', 'verbose_name_plural': 'Стаканы.'},
        ),
        migrations.AddField(
            model_name='orderbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата создания', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='orderbook',
            table='order_book',
        ),
    ]
