# Generated by Django 5.2.4 on 2025-07-18 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_alter_orderbook_options_orderbook_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waletpairs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waletpairs',
            name='slug',
            field=models.CharField(help_text='Слаг пары', max_length=255, verbose_name='Слаг пары'),
        ),
    ]
