# Generated by Django 5.2.4 on 2025-07-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_alter_waletpairs_id_alter_waletpairs_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
