# Generated by Django 5.2.4 on 2025-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия пользователя')),
                ('login', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество пользователя')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество пользователя')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
