# Generated by Django 5.2.4 on 2025-10-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_all_notifications',
            field=models.BooleanField(default=False, help_text='Получать уведомления о всех входах', verbose_name='Получать уведомления о всех входах'),
        ),
    ]
