# Generated by Django 5.2.4 on 2025-08-15 08:16

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeaccount',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(default=2, help_text='API ключ', verbose_name='API ключ'),
            preserve_default=False,
        ),
    ]
