# Generated by Django 5.2.4 on 2025-10-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_customuser_receive_all_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='receive_all_notifications',
        ),
    ]
