# Generated by Django 5.2.4 on 2025-08-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_exchangeaccount_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='exchange_account',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_exchange_account', to='trader.exchangeaccount', verbose_name='Биржевый аккаунт'),
        ),
    ]
