# Generated by Django 5.2.4 on 2025-07-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_alter_user_login_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
