# Generated by Django 5.2.4 on 2025-08-15 11:37

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_alter_customuser_exchange_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeaccount',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Пароль для аутентификации', verbose_name='Пароль'),
        ),
    ]
