# Generated by Django 5.2.4 on 2025-10-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_remove_customuser_receive_all_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.BigIntegerField(blank=True, help_text='Введите чат айди в тг если хотите получать уведомления', null=True, verbose_name='Чат айди в тг'),
        ),
    ]
