# Generated by Django 5.2.4 on 2025-08-02 17:07

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Логин для аутентификации', max_length=128, verbose_name='Логин')),
                ('password', models.CharField(help_text='Пароль для аутентификации', max_length=128, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли аккаунт', verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Биржевый аккаунт',
                'verbose_name_plural': 'Биржевые аккаунты',
                'db_table': 'exchange_account',
                'ordering': ['login'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='maximum_amount',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Максимальная сумма в рублях', verbose_name='Максимальная сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='exchange_account',
            field=models.ManyToManyField(blank=True, related_name='user_exchange_account', to='trader.exchangeaccount', verbose_name='Биржевый аккаунт'),
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP адрес прокси-сервера', verbose_name='IP адрес')),
                ('port', models.PositiveIntegerField(help_text='Порт для подключения к прокси', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Порт')),
                ('login', models.CharField(help_text='Логин для аутентификации', max_length=128, verbose_name='Логин')),
                ('password', models.CharField(help_text='Пароль для аутентификации', max_length=128, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли прокси', verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
                'db_table': 'proxy',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('ip_address', 'port', 'login', 'password'), name='unique_data_proxy')],
            },
        ),
        migrations.AddField(
            model_name='exchangeaccount',
            name='proxies',
            field=models.ManyToManyField(related_name='exchange_account_proxy', to='trader.proxy', verbose_name='Прокси'),
        ),
    ]
