# Generated by Django 5.2.4 on 2025-10-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_customuser_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='chat_id',
        ),
    ]
