# Generated by Django 5.2.4 on 2025-08-15 11:45

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_alter_exchangeaccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Пароль для аутентификации', verbose_name='Пароль'),
        ),
    ]
