# Generated by Django 5.2.4 on 2025-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_remove_customuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='protocol',
            field=models.CharField(default='http', max_length=10),
        ),
    ]
