# Generated by Django 5.2.7 on 2025-10-10 17:24

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_proxy_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='login',
            field=models.CharField(blank=True, help_text='Логин для аутентификации', max_length=128, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Пароль для аутентификации', null=True, verbose_name='Пароль'),
        ),
    ]
