# Generated by Django 5.2.7 on 2025-10-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_exchange_api_endpoint_alter_exchange_base_url_and_more'),
        ('trader', '0007_alter_proxy_login_alter_proxy_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='exchange_account',
            field=models.ManyToManyField(blank=True, related_name='user_exchange_account', to='trader.exchangeaccount', verbose_name='Биржевый аккаунт'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet_pairs',
            field=models.ManyToManyField(blank=True, related_name='customuser_wallet_pairs', to='exchange.walletpair', verbose_name='Валютные пары'),
        ),
    ]
