# Generated by Django 5.2.7 on 2025-10-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_alter_customuser_exchange_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.BigIntegerField(blank=True, help_text='Введите чат айди пользователя в тг', null=True, verbose_name='Чат айди в тг'),
        ),
    ]
