# Generated by Django 5.2.4 on 2026-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_customuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeaccount',
            name='passphrase',
            field=models.CharField(blank=True, help_text='Проверочный код', max_length=128, null=True, verbose_name='Пасс-фраза'),
        ),
    ]
