# Generated by Django 5.2.4 on 2025-08-17 09:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.PositiveIntegerField(blank=True, help_text='Маржа', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Маржа')),
                ('shoulder', models.PositiveIntegerField(blank=True, help_text='Плечо', verbose_name='Плечо')),
                ('count', models.PositiveIntegerField(help_text='Количество', verbose_name='Количество')),
                ('exit_course', models.PositiveIntegerField(help_text='Курс выхода', verbose_name='Курс выхода')),
                ('is_active', models.BooleanField(default=True, help_text='Активность', verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('wallet_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_wallet_pair', to='exchange.walletpair', verbose_name='Валютная пара')),
            ],
            options={
                'verbose_name': 'Вход',
                'verbose_name_plural': 'Входы',
                'db_table': 'entry',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_course', models.PositiveIntegerField(help_text='Курс входа', verbose_name='Курс входа')),
                ('trade_type', models.CharField(choices=[('LONG', 'Лонг'), ('SHORT', 'Шорт')], help_text='Тип сделки', verbose_name='Тип сделки')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to='trade.entry', verbose_name='Вход')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_exchange_account', to='trader.exchangeaccount', verbose_name='Биржевый аккаунт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ('-trade_type',),
            },
        ),
    ]
