# Generated by Django 5.2.4 on 2025-08-23 12:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.PositiveIntegerField(blank=True, help_text='Маржа', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Маржа')),
                ('shoulder', models.PositiveIntegerField(blank=True, help_text='Плечо', verbose_name='Плечо')),
                ('status', models.CharField(choices=[('WAIT', 'В Ожидании'), ('ACTIVE', 'Активно'), ('COMPLETED', 'Завершено')], help_text='Статус', verbose_name='Статус')),
                ('exit_course', models.PositiveIntegerField(help_text='Курс выхода', verbose_name='Курс выхода')),
                ('entry_course', models.PositiveIntegerField(help_text='Курс входа', verbose_name='Курс входа')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('exchange_accounts', models.ManyToManyField(to='trader.exchangeaccount', verbose_name='Биржевый аккаунт')),
                ('proxies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_proxy', to='trader.proxy', verbose_name='Прокси')),
                ('wallet_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_wallet_pair', to='exchange.walletpair', verbose_name='Валютная пара')),
            ],
            options={
                'verbose_name': 'Вход',
                'verbose_name_plural': 'Входы',
                'db_table': 'entry',
                'ordering': ('-created_at',),
            },
        ),
    ]
