# Generated by Django 5.2.4 on 2025-08-23 13:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='exchange_accounts',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='proxies',
        ),
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.PositiveIntegerField(blank=True, help_text='Сумма затраченная на покупку', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Маржа'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to='trade.entry', verbose_name='Вход')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_exchange_account', to='trader.exchangeaccount', verbose_name='Биржевый аккаунт')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_proxy', to='trader.proxy', verbose_name='Прокси')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
    ]
