# Generated by Django 5.2.4 on 2025-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_entry_exchange_accounts_remove_entry_proxies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_type',
            field=models.CharField(choices=[('LONG', 'Лонг'), ('SHORT', 'Шорт')], help_text='Тип сделки', verbose_name='Тип сделки'),
            preserve_default=False,
        ),
    ]
