# Generated by Django 5.2.4 on 2025-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_order_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('WAIT', 'В Ожидании'), ('ACTIVE', 'Активно'), ('COMPLETED', 'Завершено')], default='WAIT', help_text='Статус', verbose_name='Статус'),
        ),
    ]
