# Generated by Django 5.2.4 on 2025-08-26 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_entry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(help_text='Пид процесса', verbose_name='Пид процесса')),
            ],
        ),
    ]
