# Generated by Django 5.2.4 on 2025-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='entry_id',
            field=models.CharField(blank=True, help_text='ID ENTRY', verbose_name='ID ENTRY'),
        ),
    ]
