# Generated by Django 5.2.4 on 2025-09-14 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_process_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.PositiveIntegerField(blank=True, help_text='Колличество монет', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Колличество монет'),
        ),
    ]
