# Generated by Django 5.2.4 on 2025-09-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_entry_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_course',
            field=models.FloatField(help_text='Курс входа', verbose_name='Курс входа'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='exit_course',
            field=models.FloatField(help_text='Курс выхода', verbose_name='Курс выхода'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.FloatField(blank=True, help_text='Колличество монет', null=True, verbose_name='Колличество монет'),
        ),
    ]
