# Generated by Django 5.2.4 on 2025-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_alter_entry_entry_course_alter_entry_exit_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.FloatField(blank=True, help_text='Колличество контрактов', null=True, verbose_name='Колличество контрактов'),
        ),
    ]
