# Generated by Django 5.2.4 on 2025-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_alter_entry_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='exit_course',
            field=models.FloatField(blank=True, help_text='Курс выхода', null=True, verbose_name='Курс выхода'),
        ),
    ]
