# Generated by Django 5.2.4 on 2025-10-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_alter_entry_exit_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='chat_id',
            field=models.BigIntegerField(blank=True, help_text='Введите чат айди в тг если хотите получать уведомления об этом входе', null=True, verbose_name='Чат айди в тг'),
        ),
    ]
