# Generated by Django 5.2.4 on 2025-10-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_entry_chat_id'),
        ('trader', '0005_remove_customuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_proxy', to='trader.proxy', verbose_name='Прокси'),
        ),
    ]
