# Generated by Django 5.2.4 on 2025-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_alter_order_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли вход', verbose_name='Активность'),
        ),
    ]
