# Generated by Django 5.2.4 on 2025-10-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_entry_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('WAIT', 'В Ожидании'), ('ACTIVE', 'Активно'), ('COMPLETED', 'Завершено'), ('STOPPED', 'Остановлен')], default='WAIT', help_text='Статус', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_type',
            field=models.CharField(choices=[('LONG', 'Лонг'), ('SHORT', 'Шорт')], help_text='Тип сделки', max_length=50, verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='process',
            name='entry_id',
            field=models.CharField(blank=True, help_text='ID ENTRY', max_length=255, verbose_name='ID ENTRY'),
        ),
    ]
