# Generated by Django 5.2.7 on 2025-10-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_entry_alias_alter_entry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Получать уведомления в тг', verbose_name='Уведомления'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='alias',
            field=models.CharField(blank=True, help_text='Колличество контрактов', max_length=50, null=True, verbose_name='Колличество контрактов'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.FloatField(blank=True, help_text='Колличество', null=True, verbose_name='Колличество контрактов'),
        ),
    ]
