# Generated by Django 5.2.7 on 2025-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_entry_receive_notifications_alter_entry_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='receive_notifications',
        ),
        migrations.AlterField(
            model_name='entry',
            name='alias',
            field=models.CharField(blank=True, help_text='Добавьте псевдоним входа для вашего удобства', max_length=50, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.FloatField(blank=True, help_text='Колличество контрактов', null=True, verbose_name='Колличество контрактов'),
        ),
    ]
