# Generated by Django 5.2.4 on 2025-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_remove_entry_receive_notifications_alter_entry_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ex_order_id',
            field=models.CharField(blank=True, default=None, help_text='Айди ордера с биржи.', max_length=255, null=True, verbose_name='Айди ордера с биржи.'),
        ),
    ]
