# Generated by Django 5.2.7 on 2025-10-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_order_ex_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAIT', 'В Ожидании'), ('OPEN', 'Открыт'), ('CLOSED', 'Закрыт')], default='WAIT', help_text='Статус', max_length=50, verbose_name='Статус'),
        ),
    ]
