# Generated by Django 5.2.7 on 2025-10-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('WAIT', 'В Ожидании'), ('ACTIVE', 'Активно'), ('COMPLETED', 'Завершено'), ('STOPPED', 'Остановлен'), ('FAILED', 'Завершен с ошибкой')], default='WAIT', help_text='Статус', max_length=50, verbose_name='Статус'),
        ),
    ]
