# Generated by Django 5.2.7 on 2025-10-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_alter_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAIT', 'В Ожидании'), ('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('FAILED', 'Завершен с ошибкой')], default='WAIT', help_text='Статус', max_length=50, verbose_name='Статус'),
        ),
    ]
