# Generated by Django 5.2.4 on 2025-10-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reverse',
            field=models.BooleanField(db_default=False, default=True, help_text='Реверс', verbose_name='Реверс'),
        ),
    ]
