# Generated by Django 5.2.4 on 2025-10-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_entry_reverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='reverse',
            field=models.BooleanField(db_default=False, default=False, help_text='Реверс', verbose_name='Реверс'),
        ),
    ]
