# Generated by Django 5.2.4 on 2025-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0022_alter_entry_reverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.FloatField(blank=True, help_text='Колличество монет', null=True, verbose_name='Колличество монет'),
        ),
    ]
