# Generated by Django 5.2.4 on 2026-02-28 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0023_alter_entry_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('traceback', models.TextField(help_text='Текст ошибки', verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='trade.order', verbose_name='Ордер')),
            ],
            options={
                'verbose_name': 'Ошибка ордера',
                'ordering': ['-created_at'],
            },
        ),
    ]
