# Generated by Django 5.2.4 on 2026-02-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0024_errors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Errors',
            new_name='Error',
        ),
    ]
