# Generated by Django 5.2.4 on 2026-03-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0026_remove_entry_chat_id_entry_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
