# Generated by Django 5.2.4 on 2026-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0027_entry_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='shoulder',
            field=models.PositiveIntegerField(help_text='Плечо', verbose_name='Плечо'),
        ),
    ]
