# Generated by Django 5.2.4 on 2026-03-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0028_alter_entry_shoulder'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='restart',
            field=models.BooleanField(db_default=False, default=False, help_text='Перезапуск задания при завершении', verbose_name='Перезапуск задания при завершении'),
        ),
    ]
