# Generated by Django 5.2.4 on 2025-08-15 06:43

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.PositiveIntegerField(help_text='Маржа', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Маржа')),
                ('entry_rate', models.PositiveIntegerField(help_text='Курс входа', verbose_name='Курс входа')),
                ('exit_course', models.PositiveIntegerField(help_text='Курс выхода', verbose_name='Курс выхода')),
                ('is_active', models.BooleanField(default=True, help_text='Активность', verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Покупка/продажа',
                'verbose_name_plural': 'Покупка/продажа',
                'db_table': 'purchase',
                'ordering': ('-created_at',),
            },
        ),
    ]
