# Generated by Django 5.2.4 on 2025-08-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='entry_rate',
            new_name='entry_course',
        ),
    ]
