# Generated by Django 5.2.4 on 2025-08-16 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_entry_rate_purchase_entry_course'),
        ('trader', '0005_alter_proxy_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.PositiveIntegerField(help_text='Маржа', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Маржа')),
                ('shoulder', models.PositiveIntegerField(help_text='Плечо', verbose_name='Плечо')),
                ('count', models.PositiveIntegerField(help_text='Количество', verbose_name='Количество')),
                ('exit_course', models.PositiveIntegerField(help_text='Курс выхода', verbose_name='Курс выхода')),
                ('is_active', models.BooleanField(default=True, help_text='Активность', verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вход',
                'verbose_name_plural': 'Вход',
                'db_table': 'entry',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_course', models.PositiveIntegerField(help_text='Курс входа', verbose_name='Курс входа')),
                ('position', models.TextField(choices=[('LONG', 'Лонг'), ('SHORT', 'Шорт')], help_text='Позиция', verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to='purchase.entry', verbose_name='Биржа')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_exchange_account', to='trader.exchangeaccount', verbose_name='Биржа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
