# Generated by Django 5.2.4 on 2025-08-16 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_entry_order_delete_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.PositiveIntegerField(blank=True, help_text='Маржа', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Маржа'),
        ),
    ]
