# Generated by Django 5.2.4 on 2025-08-16 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_entry_profit'),
        ('trader', '0005_alter_proxy_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-created_at',), 'verbose_name': 'Вход', 'verbose_name_plural': 'Входы'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='profit',
            field=models.PositiveIntegerField(blank=True, help_text='Маржа', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Маржа'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='shoulder',
            field=models.PositiveIntegerField(blank=True, help_text='Плечо', verbose_name='Плечо'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to='purchase.entry', verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_exchange_account', to='trader.exchangeaccount', verbose_name='Биржевый аккаунт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.CharField(choices=[('LONG', 'Лонг'), ('SHORT', 'Шорт')], help_text='Позиция', verbose_name='Позиция'),
        ),
    ]
