# Generated by Django 5.2.4 on 2025-08-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_entry_options_alter_entry_profit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-trade_type',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='position',
        ),
        migrations.AddField(
            model_name='order',
            name='trade_type',
            field=models.CharField(choices=[('LONG', 'Лонг'), ('SHORT', 'Шорт')], default=1, help_text='Тип сделки', verbose_name='Тип сделки'),
            preserve_default=False,
        ),
    ]
