# Generated by Django 5.2.4 on 2025-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_order_options_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.CharField(default='', max_length=256, verbose_name='Контракт'),
        ),
    ]
