# Generated by Django 5.2.4 on 2026-03-22 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0013_exchange_is_active'),
        ('trade', '0029_entry_restart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Завершено'), ('STOPPED', 'Остановлен'), ('FAILED', 'Завершен с ошибкой')], default='COMPLETED', help_text='Статус', max_length=50, verbose_name='Статус')),
                ('profit', models.FloatField(blank=True, help_text='Колличество монет', null=True, verbose_name='Колличество монет')),
                ('shoulder', models.PositiveIntegerField(help_text='Плечо', verbose_name='Плечо')),
                ('target_entry_spread', models.FloatField(blank=True, help_text='Указанный спред входа', null=True, verbose_name='Указанный спред входа')),
                ('actual_entry_spread', models.FloatField(blank=True, help_text='Реальный спред входа', null=True, verbose_name='Реальный спред входа')),
                ('target_exit_spread', models.FloatField(blank=True, help_text='Указанный спред выхода', null=True, verbose_name='Указанный спред выхода')),
                ('actual_exit_spread', models.FloatField(blank=True, help_text='Реальный спред выхода', null=True, verbose_name='Реальный спред выхода')),
                ('pnl_percent', models.FloatField(blank=True, help_text='PNL %', null=True, verbose_name='PNL %')),
                ('pnl_currency', models.FloatField(blank=True, help_text='PNL $', null=True, verbose_name='PNL $')),
                ('time', models.DateTimeField(blank=True, help_text='Время затраченное на закрытие позиции', null=True, verbose_name='Время затраченное на закрытие позиции')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_entry', to='trade.entry')),
                ('exchange_long', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_exchange', to='exchange.exchange', verbose_name='Биржа лонг')),
                ('exchange_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_exchange', to='exchange.exchange', verbose_name='Биржа шорт')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL, verbose_name='Трейдер')),
                ('wallet_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_wallet_pair', to='exchange.walletpair', verbose_name='Валютная пара')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
                'db_table': 'analytics',
                'ordering': ('-created_at',),
            },
        ),
    ]
