# Generated by Django 5.2.4 on 2026-03-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('exchange', '0013_exchange_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='exchange_long',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_exchange', to='exchange.exchange', verbose_name='Биржа лонг'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='exchange_short',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_exchange', to='exchange.exchange', verbose_name='Биржа шорт'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Завершено'), ('STOPPED', 'Остановлен'), ('FAILED', 'Завершен с ошибкой')], default='COMPLETED', help_text='Статус', max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='wallet_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_wallet_pair', to='exchange.walletpair', verbose_name='Валютная пара'),
        ),
    ]
