# Generated by Django 5.2.4 on 2026-03-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analytics_exchange_long_and_more'),
        ('exchange', '0013_exchange_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='time',
        ),
        migrations.AddField(
            model_name='analytics',
            name='exit_time',
            field=models.DateTimeField(blank=True, help_text='Время выхода', null=True, verbose_name='Время выхода'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Время входа', null=True, verbose_name='Время входа'),
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='exchange_long',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='exchange_short',
        ),
        migrations.AddField(
            model_name='analytics',
            name='exchange_long',
            field=models.ManyToManyField(blank=True, related_name='long_exchange', to='exchange.exchange', verbose_name='Биржа лонг'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='exchange_short',
            field=models.ManyToManyField(blank=True, related_name='short_exchange', to='exchange.exchange', verbose_name='Биржа шорт'),
        ),
    ]
