# Generated by Django 5.2.4 on 2025-08-09 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Слаг пары', max_length=255, verbose_name='Слаг пары')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Валютная пара',
                'verbose_name_plural': 'Валютные пары',
                'db_table': 'walet_pair',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название биржи', max_length=255, verbose_name='Название биржи')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('wallet_pairs', models.ManyToManyField(related_name='exchange_wallet_pair', to='exchange.walletpair', verbose_name='Валютные пары')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
                'db_table': 'exchange',
                'ordering': ('name',),
            },
        ),
    ]
