# Generated by Django 5.2.4 on 2025-08-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpair',
            name='price',
            field=models.PositiveIntegerField(default=1, help_text='Стоимость', verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
