# Generated by Django 5.2.4 on 2025-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='api_endpoint',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='base_url',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
