# Generated by Django 5.2.4 on 2025-09-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_exchange_api_endpoint_exchange_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletpair',
            name='price',
        ),
        migrations.CreateModel(
            name='PairExchangeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=50, verbose_name='Локальное имя на бирже')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_mappings', to='exchange.exchange', verbose_name='Биржа')),
                ('wallet_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_mappings', to='exchange.walletpair', verbose_name='Единая пара')),
            ],
            options={
                'verbose_name': 'Маппинг пары на биржу',
                'verbose_name_plural': 'Маппинги пар на биржи',
                'ordering': ['wallet_pair', 'exchange'],
                'unique_together': {('wallet_pair', 'exchange')},
            },
        ),
    ]
