# Generated by Django 5.2.4 on 2025-09-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_pairexchangemapping_wallet_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairexchangemapping',
            name='wallet_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_mappings', to='exchange.walletpair', verbose_name='Единая пара'),
        ),
    ]
