# Generated by Django 5.2.4 on 2025-09-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_alter_pairexchangemapping_wallet_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='wallet_pairs',
        ),
    ]
