# Generated by Django 5.2.4 on 2025-09-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_remove_exchange_wallet_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='api_endpoint',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='base_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='max_limit',
            field=models.PositiveIntegerField(default=0, help_text='Максимальное кол-во', verbose_name='Максимальное кол-во'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='min_limit',
            field=models.PositiveIntegerField(default=0, help_text='Минимальное кол-во', verbose_name='Минимальное кол-во'),
        ),
    ]
