# Generated by Django 5.2.4 on 2025-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_exchange_api_endpoint_alter_exchange_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpair',
            name='coin_count',
            field=models.PositiveIntegerField(default=0, help_text='Кол-во монет в контракте', verbose_name='Кол-во монет в контракте'),
        ),
    ]
