# Generated by Django 5.2.4 on 2025-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_walletpair_coin_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletpair',
            name='coin_count',
        ),
        migrations.AddField(
            model_name='pairexchangemapping',
            name='coin_count',
            field=models.PositiveIntegerField(default=0, help_text='Кол-во монет в контракте', verbose_name='Кол-во монет в контракте'),
        ),
    ]
