# Generated by Django 5.2.4 on 2025-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_remove_walletpair_coin_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairexchangemapping',
            name='coin_count',
            field=models.FloatField(default=0, help_text='Кол-во монет в контракте', verbose_name='Кол-во монет в контракте'),
        ),
    ]
