# Generated by Django 5.2.4 on 2025-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_pairexchangemapping_coin_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairexchangemapping',
            name='min_order',
            field=models.FloatField(default=0, help_text='Минимальное количество монет для покупки', verbose_name='Минимальное количество монет для покупки'),
        ),
    ]
