# Generated by Django 5.2.4 on 2026-02-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_pairexchangemapping_min_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pairexchangemapping',
            options={'ordering': ['wallet_pair', 'exchange'], 'verbose_name': 'Локальная валютная пара', 'verbose_name_plural': 'Локальная валютная'},
        ),
        migrations.AddField(
            model_name='pairexchangemapping',
            name='normalized_name',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
