# Generated by Django 5.2.4 on 2026-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_alter_pairexchangemapping_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активна ли биржа', verbose_name='Активность'),
        ),
    ]
