# Generated by Django 5.2.4 on 2026-03-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_pairexchangemapping_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairexchangemapping',
            name='min_notional',
            field=models.FloatField(default=0, help_text='Минимальная стоимость ордера в валюте котировки (USDT)', verbose_name='Мин. номинал (USDT)'),
        ),
    ]
