# Generated by Django 5.2.4 on 2026-04-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_pairexchangemapping_min_notional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairexchangemapping',
            name='min_notional',
            field=models.FloatField(blank=True, default=None, help_text='Минимальная стоимость ордера в валюте котировки (USDT)', null=True, verbose_name='Мин. номинал (USDT)'),
        ),
    ]
